[package]
name = "yaade-desktop"
version = "0.1.0"
description = "YAADE desktop client"
edition = "2024"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
