export {
  findTerminalBufferMatch,
  maintainTerminalIdleCapacity,
  readTerminalBufferText,
  readTerminalCellHeight,
  readTerminalCellSize,
  readTerminalCursor,
  readTerminalDims,
  readTerminalLifecycle,
  readTerminalPixelStats,
  readTerminalViewportActivity,
  readTerminalViewportY,
  registerTerminalInstance,
  scrollTerminalLines,
  focusRegisteredTerminal,
  jumpRegisteredTerminalToLive,
  pasteIntoRegisteredTerminal,
  sendTerminalVirtualKey,
  setTerminalVirtualModifier,
  toggleRegisteredTerminalInspectionPause,
  unregisterTerminalInstance,
} from "./panels/terminal-instance-registry.js"
